.github/workflows/python-publish.yml
=> 📦️ Add a Github Action Workflow for Publishing the Package

.github/workflows/python-publish.yml
Inspired by: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
=> 🔨  Fix Python Release Workflow

.github/workflows/python-publish.yml
You should read the whole manual: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
=> 🔨 Fix publish workflow #2

.github/workflows/packaging_test.yml
from "coverage" to "check_packaging"
=> Rename Step in Packaging Test Action

src/maus/edifact.py, unittests/test_edifact_enums.py
copied from ahbicht, will be removed there
=> ✨ Add EDIFACT Format/Version Enums

.github/workflows/codeql-analysis.yml, .github/workflows/python-publish.yml
=> Update python packing workflow

src/maus/models/edifact_components.py, unittests/test_edifact_components.py
=> Add default values for optional properties of `SegmentGroup`

setup.cfg
so that downstream packages/service automatically upgrade
=> 🐛 Specifiy min Version of `attrs` in `setup.cfg`

README.rst
=> Change Emoji from "🐁" to "🐭"

integration_tests/helpers.py
cherry picking this from https://github.com/Hochfrequenz/mig_ahb_utility_stack/pull/61
just to proceed with other Prüfidentifikators, other than 11001/2/3
=> Add Integration Test Helper Methods

src/maus/maus_provider.py, unit_tests/test_maus_provider.py
This basically ports code that has been introduced in AHBicht to the MAUS:
https://github.com/Hochfrequenz/ahbicht/pull/158
=> ✨ Add MausProvider

src/maus/models/anwendungshandbuch.py, src/maus/models/edifact_components.py, unit_tests/test_searching_in_models.py
this feature will allow us to write concise tests against the MAUSs produced.
=> ✨ Allow searching AHBs for SegmentGroups and Segments

integration_tests/helpers.py, integration_tests/test_anmeldung_maus.py, src/maus/models/anwendungshandbuch.py, src/maus/models/edifact_components.py, unit_tests/test_searching_in_models.py
relates to https://github.com/Hochfrequenz/edifact-templates/issues/73
=> Write stricter assertions

src/maus/deep_ahb_mig_joiner.py
relates to https://github.com/Hochfrequenz/edifact-templates/pull/84
=> Prevent Flaky Tests

tests/integration_tests/test_beginn_msb_maus.py
relates to https://github.com/Hochfrequenz/edifact-templates/pull/91
=> ✔Add 11042/43/44 Integration Tests

tests/integration_tests/test_geraeteuebernahme_maus.py
relates to https://github.com/Hochfrequenz/edifact-templates/pull/92
=> ✔ Add 11057/58/59 Integration Tests

tests/integration_tests/test_ende_msb_maus.py
See https://github.com/Hochfrequenz/edifact-templates/pull/93
=> ✔ Add 11039/40/41 Integration Test

src/maus/deep_ahb_mig_joiner.py
relates to https://github.com/Hochfrequenz/edifact-templates/pull/101
=> remove restriction to only use fallbacks if no predecessor is given

tests/integration_tests/test_anmeldung_maus.py
relates to https://github.com/Hochfrequenz/edifact-templates/pull/103
=> ✔ Add 11004/5/6 Integration Test

tests/integration_tests/test_abmeldeanfrage_maus.py
relates to https://github.com/Hochfrequenz/edifact-templates/pull/113
=> ✔ Add Integration Test for 11010/11/12 (Abmeldeanfrage)

tests/integration_tests/test_abmeldung_maus.py
https://github.com/Hochfrequenz/edifact-templates/pull/116
=> ✔ Add 11007/8/9 Integration Test (Abmeldung)

tests/integration_tests/test_stammdatenaenderung_maus.py
https://github.com/Hochfrequenz/edifact-templates/pull/117
=> ✔ Add 11124 Integration Test

src/maus/models/anwendungshandbuch.py, tests/unit_tests/test_ahb.py
=> ✨ Allow Dynamic Replacement of `DataElementFreeText`.`entered_input`

.github/workflows/python-publish.yml
=> 🐛 only run tests in 📦 publish workflow

.readthedocs.yaml
copied from https://github.com/bo4e/BO4E-python/commit/5c8ef1f7d4e99b7091e5fb442c6002f9a0ed927e
=> add `.readthedocs.yaml` config file

tests/integration_tests/test_anmeldung_maus.py, tests/unit_tests/migs/FV2210/segment_group_hierarchies/sgh_utilmd.json
https://github.com/Hochfrequenz/edifact-templates/pull/168
=> Add FV2210 Integration Tests Anmeldung EOG

src/maus/deep_ahb_mig_joiner.py, tests/integration_tests/test_anmeldung_maus.py, tests/unit_tests/migs/FV2210/template_xmls/utilmd_7143.xml, tests/unit_tests/test_mig_xml_reader_real_data.py
relates to https://github.com/Hochfrequenz/edifact-templates/pull/170
=> 11002 Hacks for Gruppenartikel-ID

tests/integration_tests/test_abmeldeanfrage_maus.py, tests/integration_tests/test_abmeldung_maus.py
https://github.com/Hochfrequenz/edifact-templates/pull/171
=> Add Integration Tests for FV2210: 11007/8/9 + 11010/11/12

tests/integration_tests/test_eog_maus.py
see https://github.com/Hochfrequenz/edifact-templates/pull/172
=> Add Integration Tests for 11013/14/15

tests/integration_tests/test_stammdatenaenderung_maus.py
see also https://github.com/Hochfrequenz/edifact-templates/pull/175
=> Add Integration Test for FV2210 Stammdatenänderung

src/maus/models/anwendungshandbuch.py, src/maus/models/edifact_components.py, src/maus/transformation.py, tests/unit_tests/test_ahb.py, tests/unit_tests/test_edifact_components.py
this will be useful later on when we transform them all
=> ✨Add methods to recursively find all DataElementValuePools in a AHB

src/maus/reader/etree_element_helpers.py, tests/unit_tests/test_etree_element_helpers.py
relates to https://github.com/Hochfrequenz/edifact-templates/pull/191
=> Improve Matching of nested Qualifiers

src/maus/navigation.py, tests/unit_tests/test_navigation.py
very similar to the Edifact(Sub)Stack
=> ✨ Introduce `is_sub_location_of` for `AhbLocation`s

src/maus/edifact.py, tests/unit_tests/test_edifact_enums.py
=> 🚚 `pruefidentifikator_to_format` ➡ `get_format_of_pruefidentifikator`

.gitmodules
https://github.com/Hochfrequenz/machine-readable_anwendungshandbuecher
=> ➕📂Add `machine-readable_anwendungshandbuecher` as submodule

src/maus/transformation.py
for Bo4e Value Pool Transformations
=> Ignore Absender and Empfänger and all paths that are no json paths

tests/integration_tests/test_abmeldeanfrage_maus.py, tests/integration_tests/test_abmeldung_maus.py, tests/integration_tests/test_anmeldung_maus.py, tests/integration_tests/test_beginn_msb_maus.py, tests/integration_tests/test_ende_msb_maus.py, tests/integration_tests/test_eog_maus.py, tests/integration_tests/test_geraeteuebernahme_maus.py, tests/integration_tests/test_kuendigung_maus.py, tests/integration_tests/test_kuendigung_msb_maus.py, tests/integration_tests/test_stammdatenaenderung_maus.py, tests/unit_tests/test_navigation.py
=> Fix import paths in tests 

src/maus/__init__.py
=> Abort CLI if no argument was provided

README.rst, pyproject.toml, src/maus/cli.py
=> Make `click` an optional dependency

src/maus/models/anwendungshandbuch.py, src/maus/models/edifact_components.py, tests/unit_tests/test_ahb.py, tests/unit_tests/test_edifact_components.py
see https://github.com/Hochfrequenz/kohlrahbi/issues/304 and https://github.com/Hochfrequenz/migmose/issues/58
=> Add Segment ID to AHBLine and Segment

src/maus/edifact.py
based on https://github.com/Hochfrequenz/edifact-templates/tree/main/edi
=> added UTILMD fields in enum
